<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>ceefind</AssemblyName>
    <OutputType>Exe</OutputType>
    <RootNamespace>CeeFind</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <Product>CeeFind</Product>
    <AssemblyTitle>CeeFind</AssemblyTitle>
    <Description>Smart, all-in-one find tool with a simple index.</Description>
    <Company>George Fisher</Company>
    <Authors>George Fisher</Authors>
    <Copyright>Copyright (c) George Fisher</Copyright>
    <VersionPrefix>1.0.0</VersionPrefix>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="binary_files.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="cx.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="c.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="f.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="c.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>